### ISSUE TITLE
If Match Header value

### ISSUE THREAD

**Issue by goldytech** [oskardudycz/EventSourcing.NetCore#171]
Hi,
I was looking at the HelpDesk sample in the repo and found out that the API accepts the `If-Match` request header. I'm not sure what value needs to be passed in this header and its significance as far as versioning is concerned.

I appreciate any help you can provide.

**Comment by stavris8894** [comment]
You need to add the latest version number of the event. For example "1" if its your first call after creating it. (you need to add the "")

**Comment by dnovhorodov** [comment]
Hello,

Trying out `Helpdesk.Api` sample with the latest version from `master`. Experience following behavior:

1. Have a call to `POST /api/customers/{customerId}/incidents` to add new incident
2. Trying out `POST /api/agents/{agentId}/incidents/{incidentId}/assign` with `If-Match` header value `"1"`. Get back the following exception:
```
Marten.Exceptions.ConcurrencyException: Expected the existing version to be 1, but was 0

   at Marten.Events.FetchLivePlan`2.FetchForWriting(DocumentSessionBase session, TId id, Int64 expectedStartingVersion, CancellationToken cancellation)

   at Marten.Events.FetchLivePlan`2.FetchForWriting(DocumentSessionBase session, TId id, Int64 expectedStartingVersion, CancellationToken cancellation)
   at Marten.Events.EventStore.WriteToAggregate[T](Guid id, Int32 initialVersion, Action`1 writing, CancellationToken cancellation)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

3. Trying out `POST /api/agents/{agentId}/incidents/{incidentId}/assign` with `If-Match` header value `"0"`. Get back the following exception:
```
System.NullReferenceException: Object reference not set to an instance of an object.

   at Helpdesk.Api.Incidents.IncidentService.Handle(Incident current, AssignAgentToIncident command) in E:\GitHub\EventSourcing.NetCore\Sample\Helpdesk\Helpdesk.Api\Incidents\IncidentService.cs:line 94
   at Program.<>c__DisplayClass0_3.<<Main>$>b__20(Incident state) in E:\GitHub\EventSourcing.NetCore\Sample\Helpdesk\Helpdesk.Api\Program.cs:line 142
   at Helpdesk.Api.Core.Marten.DocumentSessionExtensions.<>c__DisplayClass1_0`1.<GetAndUpdate>b__0(IEventStream`1 stream) in E:\GitHub\EventSourcing.NetCore\Sample\Helpdesk\Helpdesk.Api\Core\Marten\DocumentSessionExtensions.cs:line 22
   at Marten.Events.EventStore.WriteToAggregate[T](Guid id, Int32 initialVersion, Action`1 writing, CancellationToken cancellation)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```
as the current of `Incident current` is `null`.
